import { Router } from "express";
import auth from "./authRoutes.js";
import farmer from "./farmerRoutes.js";
import customer from "./customerRoutes.js";
import products from "./productRoutes.js";
import uploads from "./uploadRoutes.js";
import cart from "./cartRoutes.js";
import wishlist from "./wishlistRoutes.js";
import orders from "./orderRoutes.js";
import reviews from "./reviewRoutes.js";
const router = Router();
router.use("/auth", auth);
router.use(farmer);
router.use("/customer", customer);
router.use(products);
router.use(uploads);
router.use("/cart", cart);
router.use("/wishlist", wishlist);
router.use(orders);
router.use(reviews);
export default router;
